image: python:3.7

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install jupyter pytest nbval pyyaml git+https://gitlab.com/milliams/nbpretty.git

pages:
  stage: deploy
  script:
    #- pytest --nbval *.ipynb
    - nbpretty *.ipynb
    - mkdir -p public
    - mv 00*.html index.html
    - cp *.{html,png,css} public/ || true
  artifacts:
    paths:
    - public
  only:
  - master
